services:

  proxy:
    image: gcr.io/eigr-io/functions-proxy-core:latest
    environment:
      - USER_FUNCTION_HOST=tck
      - USER_FUNCTION_PORT=8090
    command:
      - "-Dconfig.resource=dev-mode.conf"
      - "-Dcloudstate.proxy.passivation-timeout=30s"
    networks:
      - tcknet
    depends_on:
      - tck

  func:
    image: gcr.io/eigr-io/eigr-go-tck:latest
    networks:
      - tcknet

  tck:
    image: gcr.io/eigr-io/functions-tck:latest
    environment:
      - TCK_PORT=8090
      - TCK_PROXY_HOST=proxy
      - TCK_PROXY_PORT=9000
      - TCK_SERVICE_HOST=func
      - TCK_SERVICE_PORT=8080
    networks:
      - tcknet

networks:
  tcknet:
    driver: bridge